#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-etils
Version  : 0.7.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/8b/c5/69e0e75a8fc0b6cbcb69d221bc5d5653bbb0d56bb3759ccc4f9a2e60e29d/etils-0.7.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/8b/c5/69e0e75a8fc0b6cbcb69d221bc5d5653bbb0d56bb3759ccc4f9a2e60e29d/etils-0.7.1.tar.gz
Summary  : Collection of common python utils
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-etils-license = %{version}-%{release}
Requires: pypi-etils-python = %{version}-%{release}
Requires: pypi-etils-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)

%description
# Etils
[![Unittests](https://github.com/google/etils/actions/workflows/pytest_and_autopublish.yml/badge.svg)](https://github.com/google/etils/actions/workflows/pytest_and_autopublish.yml)
[![PyPI version](https://badge.fury.io/py/etils.svg)](https://badge.fury.io/py/etils)

%package license
Summary: license components for the pypi-etils package.
Group: Default

%description license
license components for the pypi-etils package.


%package python
Summary: python components for the pypi-etils package.
Group: Default
Requires: pypi-etils-python3 = %{version}-%{release}

%description python
python components for the pypi-etils package.


%package python3
Summary: python3 components for the pypi-etils package.
Group: Default
Requires: python3-core
Provides: pypi(etils)

%description python3
python3 components for the pypi-etils package.


%prep
%setup -q -n etils-0.7.1
cd %{_builddir}/etils-0.7.1
pushd ..
cp -a etils-0.7.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1660058722
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-etils
cp %{_builddir}/etils-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-etils/1128f8f91104ba9ef98d37eea6523a888dcfa5de
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-etils/1128f8f91104ba9ef98d37eea6523a888dcfa5de

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
